"""Small fixed label vocabularies keep synthetic traffic from exhausting monitoring."""

from itertools import product
from time import time

from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram

from payops.sandbox.models import Sample


class SandboxMetrics:
    """A registry per service supports separate processes and isolated ASGI tests."""

    def __init__(self) -> None:
        """Sample identifiers are intentionally absent from every metric label."""
        self.registry = CollectorRegistry()
        self.requests = Counter(
            "payment_requests_total",
            "Completed synthetic service attempts, including dependency failures",
            ("status", "processor", "region", "payment_method"),
            registry=self.registry,
        )
        self.latency = Histogram(
            "payment_authorization_latency_seconds",
            "Synthetic request latency; no financial authorization is performed",
            ("processor", "region"),
            buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10),
            registry=self.registry,
        )
        self.declines = Counter(
            "payment_declines_total",
            "Synthetic declines generated by controlled fixtures",
            ("reason", "processor"),
            registry=self.registry,
        )
        self.conflicts = Counter(
            "payment_idempotency_conflicts_total",
            "Synthetic sample ID reused with different payload or pending execution",
            registry=self.registry,
        )
        self.process_epoch = Gauge(
            "sandbox_process_start_time_seconds",
            "Service metrics registry creation time for detecting counter epoch changes",
            registry=self.registry,
        )
        self.process_epoch.set(time())
        self._initialize_slices()

    def _initialize_slices(self) -> None:
        """Known zero counters are explicit; missing series can then mean missing telemetry."""
        for status, processor, region, method in product(
            ("accepted", "declined", "error"), ("A", "B"), ("us", "eu"), ("credit", "debit")
        ):
            self.requests.labels(status, processor, region, method)
        for processor, region in product(("A", "B"), ("us", "eu")):
            self.latency.labels(processor, region)
        for processor in ("A", "B"):
            self.declines.labels("synthetic_fault", processor)

    def observe(self, sample: Sample, status: str, duration: float) -> None:
        """Only validated sample slices and closed internal statuses become labels."""
        self.requests.labels(status, sample.processor, sample.region, sample.payment_method).inc()
        self.latency.labels(sample.processor, sample.region).observe(duration)
        if status == "declined":
            self.declines.labels("synthetic_fault", sample.processor).inc()
