apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payops-observability
resources:
  - namespace.yaml
  - prometheus.yaml
configMapGenerator:
  - name: payops-prometheus-config
    files:
      - prometheus.yml
